// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XSD.Data;

#nullable disable

namespace XSD.Migrations
{
    [DbContext(typeof(ISSDbContext))]
    partial class ISSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XSD.Models.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeywordSuggestionsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeywordSuggestionsId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("XSD.Models.KeywordSuggestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("KeywordSuggestions");
                });

            modelBuilder.Entity("XSD.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeywordSuggestionsId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeywordSuggestionsId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("XSD.Models.Idea", b =>
                {
                    b.HasOne("XSD.Models.KeywordSuggestions", "KeywordSuggestions")
                        .WithMany("Ideas")
                        .HasForeignKey("KeywordSuggestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeywordSuggestions");
                });

            modelBuilder.Entity("XSD.Models.Question", b =>
                {
                    b.HasOne("XSD.Models.KeywordSuggestions", "KeywordSuggestions")
                        .WithMany("Questions")
                        .HasForeignKey("KeywordSuggestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeywordSuggestions");
                });

            modelBuilder.Entity("XSD.Models.KeywordSuggestions", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
